# Generated by Django 5.2.3 on 2025-06-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isGoogle',
            field=models.BooleanField(default=False),
        ),
    ]
